### ISSUE TITLE
Could not determine java version from '15'

### ISSUE THREAD

**Issue by erolguney** [copper-engine/copper-engine#109]
I have a new macOS image that has Java 15, but copper does not support the latest version of java.

Is that a lot of effort to support latest jdk, any indication when this will be supported?

Thanks.

**Comment by siordache** [comment]
Which version of Gradle do you use?

**Comment by erolguney** [comment]
I am using the Gradle wrapper, which needs to be upgraded to version 6.7+. Is it a large effort to upgrade the Gradle wrapper for this project?

**Comment by erolguney** [comment]
Same issue applies to the copper-starter repo.

**Comment by siordache** [comment]
Fixed in release 5.3.0.
