### ISSUE TITLE
Use Travis-CI instead of private Jenkins server

### ISSUE THREAD

**Issue by dmoebius** [copper-engine/copper-engine#37]
travis-ci.com is a public CI server which is free for OpenSource projects. See https://travis-ci.com/ , http://docs.travis-ci.com/user/getting-started/ and http://en.wikipedia.org/wiki/Travis_CI .

Every build configuration gets its full own virtual machine! It's a Ubuntu 12.04 which even comes with MySQL and Postgres, so we can run our integration tests there.

**Comment by siordache** [comment]
I configured [Travis CI](https://travis-ci.org/copper-engine/copper-engine) to build the project and run the tests using Java 10. 
We still use our private Jenkins server for publishing artifacts to Maven Central, but Travis could be configured to take care of this too. Should we get rid of Jenkins?

**Comment by dmoebius** [comment]
Great work! :) 
I'd say yes, ditch our local Jenkins. 

Would it be possible to run the tests using Java8 instead of Java10?

**Comment by siordache** [comment]
Yes, of course. I will configure Travis to use Java 8.

**Comment by siordache** [comment]
I need to configure our credentials as environment variables to allow Travis to publish the artifacts to Maven Central. Are we ok with this?

**Comment by dmoebius** [comment]
The Travis settings are protected, aren't they? Then I'd say yes.

**Comment by siordache** [comment]
Yes, they are protected.

**Comment by siordache** [comment]
Private Jenkins server deactivated. Travis-CI takes care of building, testing, and publishing the artifacts.
