### ISSUE TITLE
Support for OSGi

### ISSUE THREAD

**Issue by benfortuna** [copper-engine/copper-engine#50]
Hi,

I'm evaluating workflow engines and I was wondering if you have plans to add OSGi metadata to the manifest? I suspect it won't be too difficult as there don't appear to be many dependencies on the core library at least.

I would consider creating a pull request but just wanted to see if you object to the idea of OSGi metadata at all, or perhaps have plans for it already.

regards,
ben

**Comment by dmoebius** [comment]
Hi Ben,
no, we don't have any plans to add OSGi metadata at the moment, because we don't need it ourselves. But feel free to create a pull request, and we will evaluate it and integrate it, if it doesn't interfere with our own deploments.

Kind regards,
Dirk

**Comment by austermann** [comment]
added to 3.2.2
