### ISSUE TITLE
PreparedStatement leak  in org.copperengine.core.persistent.SqlNotify

### ISSUE THREAD

**Issue by allcolor** [copper-engine/copper-engine#58]
Hi,
there is a leak in https://github.com/copper-engine/copper-engine/blob/master/projects/copper-coreengine/src/main/java/org/copperengine/core/persistent/SqlNotify.java

The statement is created but never closed.

Regards,
Quentin Anciaux

**Comment by austermann** [comment]
Thanks for posting this issue.

You are right - the statement is not closed. When using a C3P0 Connection Pool this will not cause any problems, because c3p0 will close all resources, but users might use other datasources.
Just fixed this and some other classes in the package.
