### ISSUE TITLE
Speed up PersistentLockManager

### ISSUE THREAD

**Issue by austermann** [copper-engine/copper-engine#61]
In version 4.0 and below, a copper workflow using the `PersistentLockManager` needs at least one copper wait/notify cycle to acquire a lock, even if the lock is free. Due to the current implementation, the mechanisms in ScottyDBStorage to enhance queue updates and dequeue operations do not work for locks, i.e. there is mostly a latency of round about 500ms.
We should find a way to speed this up, because from a technical point of view there is no need to wait so long.

**Comment by dmoebius** [comment]
Do we have the same problem in `PersistenLockManagerImpl::releaseLock()`? This method also performs a DB update with a notify() following...

**Comment by austermann** [comment]
`PersistenLockManagerImpl::releaseLock()` performs the `notify` only in case that someone else is waiting for the lock to get free. So that's ok.

**Comment by austermann** [comment]
Fixed in 4.1.0
