### ISSUE TITLE
Update AuditTrail interface (Breaking with API)

### ISSUE THREAD

**Issue by theoDiefenthal** [copper-engine/copper-engine#90]
The AuditTrail interface specifies an async and sync logging function whereas async logging only makes sense for a batched auditing. So the method should be removed from the interface. 

The SpringAuditTrail from copper-spring should no longer extend BatchingAuditTrail but the AuditTrail interface directly as the batcher shouldn't be used in combination with an own transaction management.

So in one application, you should decide  whether to use a Batching audit trail with async messages or the spring audit trail with only synchronous audit trail but within the same transaction. 

This will break the API so that this change should be applied only for a new major release.

**Comment by Vladcz** [comment]
Now AuditTrail interface and SpringAuditTrail implementation have only sync methods. BatchingAuditTrail have async methods as well
