### ISSUE TITLE
Application Time vs. Database Time

### ISSUE THREAD

**Issue by rplatzdasch** [copper-engine/copper-engine#96]
Should we use database timestamp over application timestamp?

**Comment by theoDiefenthal** [comment]
Some background here:
Currently, in COPPER we use columns like `TIMESTAMP` (Postgres, Oracle, ...) without TimeZone for storing timestamps (e.g. workflow timeout). The actual value is set from the application (as `Timestamp` generated out of `System.currentTimeInMillis`, which is always in UTC). 
However, in our tests, we experienced a "shift" today where database clock and application host clock were not in sync and had a shift of a few minutes. A "wait" had thus no effect as the enqueue operation is performed as database query (in oracle default dialect) which compares the (application set) timestamp against its local time. 
@austermann Wouldn't it be better to compare timestamps from database generated against database generated or is there a reason to use application generated timestamps?

**Comment by theoDiefenthal** [comment]
I agree with setting OracleDialect as deprecated.
However, I'd still propose to switch from app time to database time in our other dialects. Especially in regards to distributed engines, having the central database manage the times will be much more resilient. If in a distributed setup, one application is out of sync in time, it can probably cause a lot of issues also for the other running applications (Which logs will look nicely as `checkClocksAreSynchronized` won't report any issues)

**Comment by austermann** [comment]
I wouldn't change it to db time. In a distributed env one should keep the clocks in sync, e.g. with NTP. And using the db time doesn't solve the problem, because when using a distributed DB (e.g. RAC) the DB nodes need to be in sync too.

**Comment by rplatzdasch** [comment]
The "central" time source also was my first thought. Get the time from a single webservice on all instances. NTP is also distributed and may not 100% sync @ all nodes. But when it comes to the webservice, you still have (as also with NTP) a problem with the repsonse time. You could add it, but then you still have the processing time, wich you could add too. At least to be 100% sync you have to correct the effect of gravity waves too. That pathological for sure.

So if it works in production as implemented ...
